version: '3'

services: 
  mongo-express:
    image: mongo-express
    ports: 
      - 8081:8081
    environment: 
      ME_CONFIG_BASICAUTH_USERNAME: achebarato
      ME_CONFIG_BASICAUTH_PASSWORD: WeGotAJob2021!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: AcheBaratoMongoDB2021!
    links: 
      - mongo
    networks: 
      - mongo-compose-network
    
  mongo:
    image: mongo
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: AcheBaratoMongoDB2021!
    ports: 
      - 27017:27017
    networks: 
      - mongo-compose-network
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: my_rabbitmq_secret
      RABBITMQ_DEFAULT_USER: achebarato
      RABBITMQ_DEFAULT_PASS: getout1123
    ports:
      - 5672:5672
      - 15672:15672

networks: 
  mongo-compose-network:
    driver: bridge